name: islami_c8_friday
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.0.15
  timezone: ^0.9.4
  just_audio: ^0.9.46
  audio_session: ^0.1.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/
